### ISSUE TITLE
[BUG] FSTAB with mount -a failed

### ISSUE THREAD

**Issue by linuxmobile** [sileshn/ArchWSL2#3]
### Requirements

- [X] Yes
- [ ] No

### CPU Architecture

- [ ] arm64
- [X] x64

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Version

Microsoft Windows [Version 10.0.25272.1000]

### Kernel Version

Default Distribution: Arch Default Version: 2

### Repro Steps

ArchWSL installs fine. But at first start it throws the following error:

```
Processing fstab with mount -a failed.

<3>WSL (10) ERROR: CreateProcessEntryCommon:570: execvpe /bin/bash failed 8
<3>WSL (10) ERROR: CreateProcessEntryCommon:579: Create process not expected to return

[process exited with code 1 (0x00000001)]
```

### Expected Behavior

I had previously tried ArchWSL and it worked perfectly for me. This is a fresh install of windows 11 and it doesn't work.

### Actual Behavior

ArchWSL installs fine. But at first start it throws the following error:

```
Processing fstab with mount -a failed.

<3>WSL (10) ERROR: CreateProcessEntryCommon:570: execvpe /bin/bash failed 8
<3>WSL (10) ERROR: CreateProcessEntryCommon:579: Create process not expected to return

[process exited with code 1 (0x00000001)]
```

**Comment by linuxmobile** [comment]
> ### Requirements
> * [x]  Yes
> * [ ]  No
> 
> ### CPU Architecture
> * [ ]  arm64
> * [x]  x64
> 
> ### WSL Version
> * [x]  WSL 2
> * [ ]  WSL 1
> 
> ### Version
> Microsoft Windows [Version 10.0.25272.1000]
> 
> ### Kernel Version
> Default Distribution: Arch Default Version: 2
> 
> ### Repro Steps
> ArchWSL installs fine. But at first start it throws the following error:
> 
> ```
> Processing fstab with mount -a failed.
> 
> <3>WSL (10) ERROR: CreateProcessEntryCommon:570: execvpe /bin/bash failed 8
> <3>WSL (10) ERROR: CreateProcessEntryCommon:579: Create process not expected to return
> 
> [process exited with code 1 (0x00000001)]
> ```
> 
> ### Expected Behavior
> I had previously tried ArchWSL and it worked perfectly for me. This is a fresh install of windows 11 and it doesn't work.
> 
> ### Actual Behavior
> ArchWSL installs fine. But at first start it throws the following error:
> 
> ```
> Processing fstab with mount -a failed.
> 
> <3>WSL (10) ERROR: CreateProcessEntryCommon:570: execvpe /bin/bash failed 8
> <3>WSL (10) ERROR: CreateProcessEntryCommon:579: Create process not expected to return
> 
> [process exited with code 1 (0x00000001)]
> ```

Fixed changing wsl -s Arch

**Comment by UndeadKernel** [comment]
I'm facing this issue with the latest release.
Using `wsl -s Arch` does not fix the issue.

**Comment by kovan** [comment]
Same here
